apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: where-for-dinner-availability.apps.local.20240529.1609.24381
spec:
  refName: where-for-dinner-availability.apps.local
  releasedAt: "2024-05-29T16:10:06Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_application_platform/where-for-dinner/where-for-dinner-availability@sha256:b0258e89dcef6860f62c076577df3401aa67a1a8a8e1d018af2f32d872913d7d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240529.1609.24381
