apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: where-for-dinner-search.apps.local.20240529.1609.24381
spec:
  refName: where-for-dinner-search.apps.local
  releasedAt: "2024-05-29T16:12:46Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_application_platform/where-for-dinner/where-for-dinner-search@sha256:603fbaeca8661ffd3dca52b39d25191dce1c2fc4a98e4e14301cbd310e377cd4
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240529.1609.24381
