apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: where-for-dinner-ui
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: dist
    path: ../..
  ports:
  - name: main
    port: 8080
  replicas: 1
  resources:
    cpu: 300m
    memory: 1Gi
