apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: where-for-dinner-crawler
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
    path: ../..
  ports:
  - name: main
    port: 8080
  replicas: 1
  resources:
    cpu: 300m
    memory: 1Gi
