---
apiVersion: v1
kind: Secret
metadata:
 name: rmq-service-overlay 
stringData:
 rmqOverlay.yaml: |
     #@ load("@ytt:overlay", "overlay")

     #@overlay/match by=overlay.subset({"kind": "ServiceBinding"}), expects="1+"
     #@overlay/match by=overlay.subset({"spec": {"service": {"name": "where-for-dinner-rabbitmq"}}}), expects=1
     --- 
     apiVersion: servicebinding.io/v1alpha3       
     spec:
       service:
         apiVersion: services.apps.tanzu.vmware.com/v1alpha1
         kind: ClassClaim
         name: where-for-dinner-rabbitmq
---
apiVersion: v1
kind: Secret
metadata:
 name: mysql-service-overlay 
stringData:
 mysqlOverlay.yaml: |
     #@ load("@ytt:overlay", "overlay")

     #@overlay/match by=overlay.subset({"kind": "ServiceBinding"}), expects="1+"
     #@overlay/match by=overlay.subset({"spec": {"service": {"name": "where-for-dinner-mysql"}}}), expects=1
     --- 
     apiVersion: servicebinding.io/v1alpha3     
     spec:
       service:
         apiVersion: services.apps.tanzu.vmware.com/v1alpha1
         kind: ClassClaim         
         name: where-for-dinner-mysql
