apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: where-for-dinner-availability
spec:
  acceptedServiceBindings:
  - name: db
    types:
    - mysql
  - name: rmq
    types:
    - rabbitmq
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
    path: ../..
  nonSecretEnv:
  - name: spring_profiles_active
    value: mysql
  ports:
  - name: main
    port: 8080
  replicas: 1
  resources:
    cpu: 300m
    memory: 1Gi
