apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  creationTimestamp: null
  name: where-for-dinner-notify
spec:
  acceptedServiceBindings:
  - name: rmq
    types:
    - rabbitmq
  content:
    packageRefName: where-for-dinner-notify.apps.local.20240502.0.851768000
    packageVersion: 20240502.0.851768000
  image: reg.perfect300rock.com/tapdev/where-for-dinner-notify@sha256:eaf490019f9baef6c5117bc28e544bdc3b6310f34475cbc469b93ac47a59b45f
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=where-for-dinner-notify
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: where-for-dinner-notify
  - for: kubernetes.service-target
    kind: Service
    name: where-for-dinner-notify
  - for: kubernetes.scale-replicas
    keyPath: .data.'values\.yml'->[yaml].replicas
    kind: Secret
    name: where-for-dinner-notify
  - for: kubernetes.scale-resources
    keyPath: .data.'values\.yml'->[yaml].resources
    kind: Secret
    name: where-for-dinner-notify
  - for: kubernetes.set-secret-env
    keyPath: .data.'values\.yml'->[yaml].secretEnv
    kind: Secret
    name: where-for-dinner-notify
  resources:
    cpu: 300m
    memory: 1Gi
