apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: where-for-dinner-notify.apps.local.20240502.0.851768000
spec:
  refName: where-for-dinner-notify.apps.local
  releasedAt: "2024-05-02T14:45:49Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: reg.perfect300rock.com/tapdev/where-for-dinner-notify@sha256:d6656af4780497e5914e394fe65c246d51c607b565ac83bc2460a5a02b9a55c5
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240502.0.851768000
