apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: where-for-dinner-notify.apps.local.20240510.1234.21994
spec:
  refName: where-for-dinner-notify.apps.local
  releasedAt: "2024-05-10T12:39:52Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_application_platform/where-for-dinner/where-for-dinner-notify@sha256:4f2a49b13112db59e4cd10d20622e7d1f71cf13e6a5fbf46c966db63b78f3164
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240510.1234.21994
