---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: PreProvisionedService
metadata:
  name: where-for-dinner-mysql
spec:
  bindingConnectors:
  - name: read-write
    description: Read-write MySQL available in all availability targets
    type: mysql
    secretRef: 
      name: where-for-dinner-mysql
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: PreProvisionedService
metadata:
  name: where-for-dinner-rabbitmq
spec:
  bindingConnectors:
  - name: read-write
    description: Read-write message broker available in all availability targets
    type: rabbitmq
    secretRef: 
      name: where-for-dinner-rabbitmq
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-availability-mysql
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: availability
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-mysql
    connectorName: read-write
  alias: db
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-search-mysql
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: where-for-dinner-search
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-mysql
    connectorName: read-write
  alias: db
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-availability-rabbitmq
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: availability
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-rabbitmq
    connectorName: read-write
  alias: rmq
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-search-rabbitmq
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: where-for-dinner-search
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-rabbitmq
    connectorName: read-write
  alias: rmq
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-search-proc-rabbitmq
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-proc
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-rabbitmq
    connectorName: read-write
  alias: rmq
---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: ServiceInstanceBinding
metadata:
  name: where-for-dinner-notify-rabbitmq
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: where-for-dinner-notify
  serviceInstanceRef:
    apiVersion: services.tanzu.vmware.com/v1alpha1
    kind: PreProvisionedService
    name: where-for-dinner-rabbitmq
    connectorName: read-write
  alias: rmq