apiVersion: config.tanzu.vmware.com/v1
kind: TanzuConfig
children:
- ../where-for-dinner/where-for-dinner-search
- ../where-for-dinner/where-for-dinner-availability
- ../where-for-dinner/where-for-dinner-crawler
- ../where-for-dinner/where-for-dinner-notify
- ../where-for-dinner/where-for-dinner-search-proc
- ../where-for-dinner/where-for-dinner-ui
configuration:
  dev:
    paths:
    - .tanzu/config/