apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: where-for-dinner-search-proc.apps.local.20240510.1234.21994
spec:
  refName: where-for-dinner-search-proc.apps.local
  releasedAt: "2024-05-10T12:41:33Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_application_platform/where-for-dinner/where-for-dinner-search-proc@sha256:3799fa96728b9c642f348d2a90f36f568656bb87c83e42f1b093c6c11257e251
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240510.1234.21994
